version: '3'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel
    volumes:
      - ../:/var/www/point-justification
    networks:
      - point-justification
    ports:
      - 9000:9000
    command: [sh, -c, "php -f point-justification/artisan serve --host=0.0.0.0 --port=9000"]

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=pointjustification
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - point-justification

networks:
  point-justification:
    driver: bridge
